### ISSUE TITLE
TODO: evaluate additional CIs

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#207]
* [ ] Circle CI _(in progress)_
* [ ] Shippable (they have recently announced macOS and Windows support) / _https://twitter.com/webKnjaZ/status/991415221834141696_
* [ ] GitLab CI
* [ ] Wercker
* [ ] Semaphore / https://github.com/marketplace/semaphore/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW41MjA=#pricing-and-setup
* [ ] Codefresh / https://github.com/marketplace/codefresh
* [ ] Buddy / https://github.com/marketplace/buddy/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW45MDM=#pricing-and-setup / https://buddy.works/knowledge/automation/how-build-and-deploy-python

##### Misc
- https://github.com/menegazzo/travispy/blob/3bdbf9b0fa3b89b8efbdccef50e077ef8f27fad8/docs/getting_started.rst
- https://www.npmjs.com/package/github-auto-deploy
- https://github.com/github/github-services/commit/ad96b9710eccb2e4531bc2964399980907ebf65f
- https://developer.github.com/v3/activity/events/types/#deploymentevent
- https://developer.github.com/v3/repos/deployments/#create-a-deployment
- https://buildkite.com/blog/github-deployments
- https://github.com/marketplace/category/deployment
- https://developer.github.com/v3/guides/automating-deployments-to-integrators/
- https://developer.github.com/changes/2014-01-09-preview-the-new-deployments-api/
- https://github.com/issc29/jenkins-deployment-api
- https://developer.github.com/v3/guides/delivering-deployments/

**Comment by asvetlov** [comment]
Azure Pipelines is the our choice, at least until Github Actions don't support external templates.
