### ISSUE TITLE
TODO: investigate a better tooling for building wheels (especially OS X ones)

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#266]
* [ ] https://github.com/matthew-brett/multibuild/blob/devel/osx_utils.sh
* [ ] https://github.com/joerick/cibuildwheel
* [ ] https://www.youtube.com/watch?v=d-p6lJJObLU
* [ ] https://www.google.com.cy/search?q=building+python+os-specific+wheels+for+osx
* [ ] https://us.pycon.org/2015/schedule/presentation/377/
* [ ] https://www.youtube.com/watch?v=d-p6lJJObLU
* [ ] https://lepture.com/en/2014/python-on-a-hard-wheel (`macosx_10_6_intel` -> )

  We need at least:
  - `macosx_10_6_intel`
  - `macosx_10_9_x86_64`
  - `macosx_10_10_x86_64`
  - `macosx_10_11_x86_64`
  - `macosx_10_12_x86_64`
  - `macosx_10_13_x86_64`

  Questionable:
  - `macosx_10_9_intel`
  - `macosx_10_10_intel`
  - `macosx_10_11_intel`
  - `macosx_10_12_intel`
  - `macosx_10_13_intel`
* [ ] https://github.com/MacPython/wiki/wiki/Wheel-building
* [ ] https://github.com/MacPython/wiki/wiki/Spinning-wheels
* [ ] https://pypi.org/project/Cython/#files (see platform tags)
* [ ] https://github.com/MacPython/wiki/wiki/Which-Python
* [ ] https://www.python.org/downloads/mac-osx/ (get official python dists from there)
  - https://github.com/wolfSSL/wolfcrypt-py/blob/9f70f72cb6d1855a2c8809ccc5c134296c65bb6c/make/osx/install_python.sh
  - https://github.com/wolfSSL/wolfcrypt-py/blob/9f70f72cb6d1855a2c8809ccc5c134296c65bb6c/make/osx/build_wheels.sh
  - https://github.com/wolfSSL/wolfcrypt-py/blob/9f70f72cb6d1855a2c8809ccc5c134296c65bb6c/Makefile#L82-L89
  - https://github.com/wolfSSL/wolfcrypt-py/blob/9f70f72cb6d1855a2c8809ccc5c134296c65bb6c/.travis.yml
  - https://www.python.org/ftp/python/
* [ ] https://github.com/rlhelinski/hdbscan-wheels/commit/f01d734f0b8c167fd6c02534a5c18b1b4cf836db
  https://github.com/pypa/twine/issues/273
* [ ] https://www.google.cz/search?q=python+setup.cfg+wheel+plat-name
  `--plat-name` doesn't work for passing multiple dot-separated plat-names, because dots are normalized as `_`.
* [ ] https://www.python.org/dev/peps/pep-0425/
* [ ] https://packaging.python.org/guides/distributing-packages-using-setuptools/
* [ ] https://github.com/SynBioDex/pySBOL/wiki/Uploading-Wheels-(pip)
* [ ] https://pypi.org/project/wheel/ | https://wheel.readthedocs.io/en/stable/
* [ ] https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce
* [ ] https://docs.travis-ci.com/user/reference/osx/
* [ ] https://github.com/pypa/pip/pull/1465#issuecomment-37094250
  - https://github.com/MacPython/scipy-stack-osx-testing
  - https://github.com/matplotlib/mpl_mac_testing
* [ ] https://github.com/ogrisel/wheelhouse-uploader
* [ ] https://www.google.com.cy/search?q=python+MACOSX_DEPLOYMENT_TARGET
* [ ] https://stackoverflow.com/a/25362535/595220
* [ ] https://github.com/lepture/mistune/commit/3ae489adfa4b8b8b26391c44c0d093e628c330d5
* [ ] https://gist.github.com/matthew-brett/51bdd3c817bd6541b950 (`POP_PLAT_TAG`, `SYS_PLAT_TAG`, `BREW_PLAT_TAG`?)
* [ ] https://github.com/pypa/pip/blob/master/pyproject.toml
* [ ]

**Comment by asvetlov** [comment]
I think we are fine with GitHub workflows

**Comment by webknjaz** [comment]
We still need to use delocate (auditwheel's counterpart for OS X)

**Comment by asvetlov** [comment]
I don't aware of any problem with our MacOS wheels provided.
My co-workers who use Mac also look happy :)

I think this is because we just don't bundle external shared libraries into aio-libs projects but statically link everything except the stdlib and Python itself.

**Comment by samuelcolvin** [comment]
I can thoroughly recommend github actions for generating wheels for all major.

Look at pydantic for an example of generating all wheels then uploading them all together.
