### ISSUE TITLE
[TODO] Migrate `tests/gen_pickles.py` into a pytest fixture

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/multidict#922]
The idea is simple:
* [ ] Make a session-scoped fixture in `tests/conftest.py`
* [ ] Move the logic from `gen_pickles.py` there and generate the pickles in a `tmppath`-provided dir
* [ ] Integrate that into the pickling tests
* [ ] Delete `tests/gen_pickles.py` and the pickle files in the `tests/` dir
* [ ] _Bonus points_: keep pickles in-memory, so they don't hit the disk
* [ ] _Bonus 2_: check if a session fixture is needed and switch to the normal function scope, if not

**Comment by vrdn-23** [comment]
I've raised a PR here (https://github.com/aio-libs/multidict/pull/924). I think this addresses the ideas mentioned here. let me know if there's a better way to do this or if I'm barking up the wrong tree completely!
Thanks for all your help so far!

**Comment by webknjaz** [comment]
I'll have a number of comments in the review there.

**Comment by vrdn-23** [comment]
Sounds good. Let me know!

**Comment by Jamim** [comment]
Hello @vrdn-23 and @webknjaz,

I tried to fix #924 locally and after a few iterations of a simplification I realized that the [`test_load_from_file`](https://github.com/aio-libs/multidict/blob/master/tests/test_pickle.py#L24-L38) test doesn't increase coverage since there's already the [`test_pickle`](https://github.com/aio-libs/multidict/blob/master/tests/test_pickle.py#L9-L14) test that **does exactly the same**, but in a more elegant and easy to understand way. If I didn't miss something, it's implicitly parametrized enough to cover all the cases. The only difference is that the initial implementation of `test_load_from_file` checks whether data pickled with some previous version of the `multidict` library still can be unpickled and matched with the current version data, but _if you are going to eliminate the corresponding files_, it seems reasonable to drop the `test_load_from_file` completely and rely on the `test_pickle` instead.

@webknjaz what do you think?

**Comment by webknjaz** [comment]
Feel free to submit an alternative PR.

**Comment by webknjaz** [comment]
I concluded that we should integrate one of pytest-harvest, pytest-datadir, python-pytest-cases or pytest-regressions instead. This needs some research.

**Comment by asvetlov** [comment]
Sorry, I object to removing pickle files stored on the disk.

These files were added intentionally to ensure that newer multidict versions still could read older pickles.
All this code was added during the bugfix for an accident with broken backward compatibility.

@webknjaz please feel free to reword the issue to keep pickle files and the generator. Honestly, I prefer keeping everything as is but moving `tests/gen_pickles.py` file to `tools` folder.

**Comment by webknjaz** [comment]
Using a proper pytest plugin will address this. Being so disorganized what was prompted the idea of removal since it wasn't obvious what the purpose was. Using a plugin will communicate that clearly.

**Comment by asvetlov** [comment]
I'm ok with a plugin if it keeps pickled files in the git tree.

**Comment by webknjaz** [comment]
@Vizonex it would be helpful if you could make 4 PRs for comparison to demonstrate the difference to the maintainers. But if not, at least a comment with advantages/drawbacks/maintainability would be nice too. Upon this, we'll commit to using one plugin consistently and across projects.

**Comment by Vizonex** [comment]
> Plugins to choose from:
> 
> * `pytest-harvest`:  https://smarie.github.io/python-pytest-harvest
> * `syrupy`: https://til.simonwillison.net/pytest/syrupy / https://syrupy-project.github.io/syrupy
> * `pytest-insta`: https://github.com/vberlier/pytest-insta
> * `inline-snapshot`:  https://15r10nk.github.io/inline-snapshot

Let me make a checklist so that I don't forget which ones I have compelted already for making draft-prs for.
* [x] pytest-harvest #1270
* [ ] syrupy 
* [ ] pytest-insta
* [ ] inline-snapshot
